lib/ciao_web/router.ex
defmodule CiaoWeb.Router do
  use CiaoWeb, :router

  import CiaoWeb.UserAuth

  @policy "default-src 'self'\ 'self' * blob: data: image;"

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {CiaoWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers, %{"content-security-policy" => @policy})
    plug(:fetch_current_user)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :live_pipeline do
    plug(:put_layout, {CiaoWeb.LayoutView, :live})
    plug(:require_authenticated_user)
  end

  pipeline :live_pipeline_unauthenticated do
    plug(:put_layout, {CiaoWeb.LayoutView, :live})
  end

  scope "/", CiaoWeb do
    pipe_through([:browser, :live_pipeline_unauthenticated, :redirect_if_user_is_authenticated])

    live("/", PageLive.Index)
    live("/log_in", PageLive.LogIn)
  end

  scope "/app", CiaoWeb do
    pipe_through([:browser, :live_pipeline])

    live("/places", PlaceLive.Index)
    live("/places/:id_or_slug", PlaceLive.Show)
    live("/account", AccountLive.Index)
  end

  # Other scopes may use custom stacks.
  # scope "/api", CiaoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: CiaoWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end

  ## Authentication routes

  scope "/", CiaoWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    get("/users/register", UserRegistrationController, :new)
    post("/users/register", UserRegistrationController, :create)
    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
    put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/", CiaoWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/users/settings", UserSettingsController, :edit)
    put("/users/settings", UserSettingsController, :update)
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)
  end

  scope "/", CiaoWeb do
    pipe_through([:browser])
    get("/users/invite/:token", UserInviteController, :create)
  end

  scope "/", CiaoWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    delete("/users/log_out", UserSessionController, :delete)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :edit)
    post("/users/confirm/:token", UserConfirmationController, :update)
    get("/users/sign_in/confirm", UserSessionController, :magic)
    get("/users/sign_in/:token", UserSessionController, :sign_in)
    get("/users/new_password/:token", UserResetPasswordController, :new_login)
    put("/users/new_password/:token", UserResetPasswordController, :new_create)
  end
end

lib/ciao_web/views/layout_view.ex
defmodule CiaoWeb.LayoutView do
  use CiaoWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/ciao_web/templates/layout/_mobile_menu.html.heex
<%= if @current_user do %>
    <div class="mobile-nav--secondary f-row">
        <button class="mobile-nav--btn" id="show-places--btn" data-panel="places-list--panel">
            Places
        </button>
    </div>
<% end %>
    

lib/ciao_web/templates/layout/_submenu.html.heex
<%= if @current_user do %>
<div class="submenu">

</div>
<% end %>

lib/ciao_web/templates/layout/_user_menu.html.heex
<div class="navbar-menu f-row self-center">
    <div class="navbar-collapse">
        <ul>
            <%= if @current_user do %>
            <li><%= @current_user.email %></li>
            <li><%= link "Places", to: Routes.live_path(@conn, CiaoWeb.PlaceLive.Index) %></li>
            <li><%= link "Account", to: Routes.user_settings_path(@conn, :edit) %></li>
            <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
            <% else %>
            <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
            <li><%= link "Log in", to: Routes.live_path(@conn, CiaoWeb.PageLive.LogIn) %></li>
            <% end %>
        </ul>
    </div>
    <div class="navbar-mobile--icon" >
       	<span />
       	<span />
       	<span />
    </div>
</div>

lib/ciao_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/ciao_web/templates/layout/email.html.heex
 <!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
    <style>
      @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&display=swap');
      @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,700;1,200;1,400;1,700&display=swap');
      body {
        font-family: "Montserrat", sans-serif;
        font-size: 16px;
      }

      h2 {
        font-family: 'DM Serif Display', serif;
        font-size: 20px;
        color: #1F1D41;
      }

      @media screen and (min-width: 600px) {
        h2x {
          font-size: 32px;
        }
      }

      .header-banner {
        display: flex;
        justify-content: center;
        padding-top: 10px;
        padding-bottom: 10px;
        min-height: 50px;
        width: 100%;
        background-color: #bcf0cd;
      }
    </style>
  </head>
  <body>
    <%= @inner_content %> 
  </body>

</html>

lib/ciao_web/templates/layout/live.html.heex
<main class="container">
</main>

lib/ciao_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Ciao", suffix: " - The Anti-social social network" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section>
        <nav>
        <div class="f-row self-center">
            <h1>Ciao</h1>
          </div>
          <%= render "_user_menu.html", assigns %>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>